### ISSUE TITLE
pkg_resources.DistributionNotFound: cryptography>=0.7

### ISSUE THREAD

**Issue by droope** [roglew/pappy-proxy#1]
Hi there,

Keen on trying pappy out, but after following the installation instructions,  creating a a folder and running pappy from the command line I get the following error:

<pre>
[root@debian-dev test_project]# pappy
Traceback (most recent call last):
  File "/usr/local/bin/pappy", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 451, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 464, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: cryptography>=0.7
</pre>

I am not sure what the problem is. The output of pip freeze on my debian box is here http://pastie.org/private/f30wsdno81nxsk4ifypba

I tried installing the dependency mentioned on that error but that is already installed. Attempting an upgrade fails with an "ImportError: No module named setuptools_ext" error. I have python-setuptools on that box.

Thanks!
Pedro

**Comment by roglew** [comment]
Looking at your pip freeze, it looks like the cryptography library is an older version than the dependency requirements expect. When you say you attempted an upgrade, do you mean you tried to update the cryptography library?
