### ISSUE TITLE
root permissions & openssl/aes.h file not found

### ISSUE THREAD

**Issue by avivais** [roglew/pappy-proxy#10]
Running with user permissions:

```
$ python setup.py install
Checking .pth file support in /Library/Python/2.7/site-packages/
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/test-easy-install-12740.pth'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /Library/Python/2.7/site-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://pythonhosted.org/setuptools/easy_install.html

Please make the appropriate changes for your system and try again.
```

Running with sudo:
$ sudo python setup.py install
Generates some warning, and then the fatal error:

```
scrypt-1.1.6/lib/crypto/crypto_aesctr.c:38:10: fatal error: 'openssl/aes.h' file not found
```

Then when trying to execute:

```
$ pappy -l
Traceback (most recent call last):
  File "/usr/local/bin/pappy", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2793, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 673, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 576, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: scrypt>=0.7.1
```

Running under El Capitan 10.11.6

**Comment by roglew** [comment]
I think there is some dependency for scrypt that you do not have installed. I vaguely remember running into this a while ago but I must have just fixed it myself and forgotten to document it. Sicne a dependency is missing, the scrypt library isn't being installed. Then because Pappy depends on the library, Pappy isn't being run. I don't know what the dependency is off the top of my head unfortunately. I suggest setting up a virtual environment and seeing if you can install the scrypt by itself.

**Comment by roglew** [comment]
No update for a while, closing. If you still have this problem, feel free to post an update and we can reopen this.
