### ISSUE TITLE
Error running `pappy -l` after `pip install .`

### ISSUE THREAD

**Issue by ItsMeVlad** [roglew/pappy-proxy#18]
I'm unable to run pappy due to what appears to be an unmet dependancy.

#### Install
```
$ git clone --recursive https://github.com/roglew/pappy-proxy.git
$ cd pappy-proxy
$ pip install .
$ mkdir natas
$ cd natas
```

#### Run ```pappy -l```
```
Traceback (most recent call last):
  File "/usr/local/bin/pappy", line 11, in <module>
    load_entry_point('pappyproxy==0.3.1', 'console_scripts', 'pappy')()
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 567, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 2604, in load_entry_point
    return ep.load()
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 2264, in load
    return self.resolve()
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 2270, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named pappyproxy.pap
```

### Versions
pip Version: ```9.0.1```
Python Version: ```2.7```

What needs to be installed in order to meet the pappyproxy.pap requirement?

**Comment by RickTorresJr** [comment]
Can confirm this is also happening in Kali Rolling when installed from source:

```
pappy -l
Traceback (most recent call last):
  File "/usr/local/bin/pappy", line 7, in <module>
    from pappyproxy.pap import start
ImportError: No module named pappyproxy.pap
```

OS: `4.12.0-kali2-amd64 #1 SMP Debian 4.12.12-2kali1 (2017-09-13) x86_64 GNU/Linux`
Python: `Python 2.7.13`
Pip: `pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)`
