### ISSUE TITLE
Error while installing pappy via pip on Kali Rolling 2017.2

### ISSUE THREAD

**Issue by RickTorresJr** [roglew/pappy-proxy#19]
```
pip install pappy
Collecting pappy
  Using cached pappy-0.91.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-pJrzAI/pappy/setup.py", line 2, in <module>
        from Pyrex.Distutils.extension import Extension
    ImportError: No module named Pyrex.Distutils.extension
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-pJrzAI/pappy/
```

OS Info:
4.12.0-kali2-amd64 #1 SMP Debian 4.12.12-2kali1 (2017-09-13) x86_64 GNU/Linux

Python:
Python 2.7.13

Pip:
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)

**Comment by noraj** [comment]
Same with Archlinux, Python 3.6.6, Python 2.7.15, `pip 18.0 from /usr/lib/python2.7/site-packages/pip (python 2.7)` and `pip 18.0 from /usr/lib/python3.6/site-packages/pip (python 3.6)`.

**Comment by noraj** [comment]
pyres is not in your `setup.py`, is not available on pypi for our python/pip versions, and is not listed on your requirements.
