### ISSUE TITLE
error during ./start on 4.13.10-1kali2

### ISSUE THREAD

**Issue by shellchocolat** [roglew/pappy-proxy#21]
./install.sh seems fine:
```bash
No GOPATH detected, creating temporary GOPATH at /root/Github/pappy-proxy/gopath
Already up to date.
Getting puppy dependencies...
Building puppy into /root/.pappy/puppy...
Running virtualenv with interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /root/.pappy/venv/bin/python3
Not overwriting existing python script /root/.pappy/venv/bin/python (you must use /root/.pappy/venv/bin/python3)
Installing setuptools, pip, wheel...done.
Obtaining file:///root/Github/pappy-proxy
Requirement already satisfied: cmd2>=0.6.8 in /root/.pappy/venv/lib/python3.6/site-packages (from pappyproxy==0.3.1) (0.9.2)
Requirement already satisfied: Jinja2>=2.8 in /root/.pappy/venv/lib/python3.6/site-packages (from pappyproxy==0.3.1) (2.10)
Requirement already satisfied: pygments>=2.0.2 in /root/.pappy/venv/lib/python3.6/site-packages (from pappyproxy==0.3.1) (2.2.0)
Requirement already satisfied: pyperclip>=1.5.27 in /root/.pappy/venv/lib/python3.6/site-packages (from cmd2>=0.6.8->pappyproxy==0.3.1) (1.6.2)
Requirement already satisfied: colorama in /root/.pappy/venv/lib/python3.6/site-packages (from cmd2>=0.6.8->pappyproxy==0.3.1) (0.3.9)
Requirement already satisfied: wcwidth; sys_platform != "win32" in /root/.pappy/venv/lib/python3.6/site-packages (from cmd2>=0.6.8->pappyproxy==0.3.1) (0.1.7)
Requirement already satisfied: MarkupSafe>=0.23 in /root/.pappy/venv/lib/python3.6/site-packages (from Jinja2>=2.8->pappyproxy==0.3.1) (1.0)
Installing collected packages: pappyproxy
  Found existing installation: pappyproxy 0.3.1
    Uninstalling pappyproxy-0.3.1:
      Successfully uninstalled pappyproxy-0.3.1
  Running setup.py develop for pappyproxy
Successfully installed pappyproxy

Pappy installed. Run pappy by executing the generated "start" script.
```

But there is an issue when .start
```bash
Traceback (most recent call last):
  File "/root/.pappy/venv/bin/pappy", line 11, in <module>
    load_entry_point('pappyproxy', 'console_scripts', 'pappy')()
  File "/root/Github/pappy-proxy/pappyproxy/pap.py", line 142, in start
    main()
  File "/root/Github/pappy-proxy/pappyproxy/pap.py", line 134, in main
    interface_loop(client)
  File "/root/Github/pappy-proxy/pappyproxy/console.py", line 32, in interface_loop
    cons.cmdloop()
  File "/root/.pappy/venv/lib/python3.6/site-packages/cmd2/cmd2.py", line 3052, in cmdloop
    parser = argparse.ArgumentParser()
  File "/usr/lib/python3.6/argparse.py", line 1631, in __init__
    prog = _os.path.basename(_sys.argv[0])
IndexError: list index out of range

```

**Comment by hook-s3c** [comment]
also having this issue

**Comment by SimoneRaponi** [comment]
I'm having the same issue, in Ubuntu 18.04.1 LTS.
Has anyone solved the problem?

**Comment by Holzhaus** [comment]
Also having this issue on Arch Linux.

**Comment by Holzhaus** [comment]
Looks like [line 31 in pappyproxy/console.py](https://github.com/roglew/pappy-proxy/blob/e1bb049ef0f0c1f208fb3e35ef3c82eca3043300/pappyproxy/console.py#L31) is culprit. If you comment that one out, the error goes away.
