### ISSUE TITLE
List index out of range when running pappy --lite without SSL certificates

### ISSUE THREAD

**Issue by Holzhaus** [roglew/pappy-proxy#22]
```
$ pappy --lite
could not load certificate pair: open /home/jan/.pappy/certs/server.pem: no such file or directory
Would you like to generate the certificates now?
(Y/n) y
Certificates generated to /home/jan/.pappy/certs
Be sure to add /home/jan/.pappy/certs/server.pem to your trusted CAs in your browser!
Traceback (most recent call last):
  File "/usr/bin/pappy", line 11, in <module>
    load_entry_point('pappyproxy==0.3.1', 'console_scripts', 'pappy')()
  File "/usr/lib/python3.7/site-packages/pappyproxy/pap.py", line 142, in start
    main()
  File "/usr/lib/python3.7/site-packages/pappyproxy/pap.py", line 134, in main
    interface_loop(client)
  File "/usr/lib/python3.7/site-packages/pappyproxy/console.py", line 32, in interface_loop
    cons.cmdloop()
  File "/usr/lib/python3.7/site-packages/cmd2/cmd2.py", line 3598, in cmdloop
    parser = argparse.ArgumentParser()
  File "/usr/lib/python3.7/argparse.py", line 1641, in __init__
    prog = _os.path.basename(_sys.argv[0])
IndexError: list index out of range
```

**Comment by Holzhaus** [comment]
look like it's a duplicate of #21
