### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by j3rrykh4n** [roglew/pappy-proxy#27]
pappy: error: unrecognized arguments: -l
 ✘  ~/p/jerry   master   pappy
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/pappy", line 11, in <module>
    load_entry_point('pappyproxy==0.3.1', 'console_scripts', 'pappy')()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/pappyproxy/pap.py", line 142, in start
    main()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/pappyproxy/pap.py", line 92, in main
    with ProxyClient(binary=binloc, conn_addr=msg_addr, debug=args.debug) as client:
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/pappyproxy/proxy.py", line 1173, in __enter__
    self.execute_binary(binary=self.binloc, debug=self.debug)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/pappyproxy/proxy.py", line 1201, in execute_binary
    self.proxy_proc = Popen(args, stdout=PIPE, stderr=PIPE)
  File "/data/data/com.termux/files/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/data/data/com.termux/files/usr/lib/python3.7/subprocess.py", line 1520, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/data/data/com.termux/files/home/storage/storage/sdcard0/htdocs/go/bin/puppy': '/data/data/com.termux/files/home/storage/storage/sdcard0/htdocs/go/bin/puppy'
 ✘  ~/

...its gave me this error how can i fix this bro

**Comment by rudSarkar** [comment]
use
`$ sudo pappy`

**Comment by janskyview** [comment]
Hi, 

sudo does not work for me...anyone found any solution to this? 
Upon sudo I get: 
Authorization required, but no authorization protocol specified

xsel: Can't open display: (null)
: Resource temporarily unavailable
Could not find puppy binary in GOPATH or ~/.pappy. Please ensure that it has been compiled, or pass in the binary location from the command line
